---
title: "Análisis de datos de COVID-19 en Costa Rica - Gráficos del paquete base"
author: "Sofía Carpio"
date: '2022-05-11'
output:
  html_document:
    theme: readable    
    toc: true
    toc_depth: 5
    toc_float:
      collapsed: false
      smooth_scroll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Presentación 
Este documento presenta gráficos generados a partir de los datos de COVIC-19 en Costa Rica compartidos por el Ministerio de Salud en [https://geovision.uned.ac.cr/oges/](https://geovision.uned.ac.cr/oges/)

## Entradas
```{r carga-datos}
covid <- read.csv(file = "05_10_22_CSV_GENERAL.csv", sep = ";")
```


## Procesamiento 

## Opciones generales 
```{r opciones generales}
options(scipen = 7)
```


### Curación de datos 
```{r conversion-fecha}
covid$FECHA <- as.Date(covid$FECHA, format = "%d/%m/%Y")
```


## Salidas 

### Gráficos 

#### Casos acumulados 

##### Positivos  
```{r casos-positivos-acumulados}
plot(
  covid$FECHA,
  covid$positivos, 
  type = "l",
  xaxt = "n",
  yaxt = "n", 
  main = "Casos acumulados positivos de COVID-19 en Costa Rica", 
  xlab = "Fecha",
  ylab = "Casos")

axis(
  side = 1,
  covid$FECHA,
  tick = FALSE,
  format(covid$FECHA, "%m-%y"),
  cex.axis = 0.7
) 
axis(
  side = 2,
  covid$positivos,
  labels = TRUE,  
  at = seq(0, 1000000, by = 200000),
  cex.axis = .7
)
```



##### Fallecidos
```{r casos-fallecidos-acumulados}
plot(
  covid$FECHA,
  covid$fallecidos,
  type = "l",
  xaxt = "n",
  yaxt = "n",
  main = "Casos fallecidos acumulados de COVID en Costa Rica",
  xlab = "Fecha",
  ylab = "Casos fallecidos"
)

axis(side = 1,
     covid$FECHA,
     tick = FALSE,
     format(covid$FECHA, "%m-%y"),
     cex.axis = .7)

axis(side = 2,
  covid$fallecidos,
  labels = TRUE,  
  at = seq(0, 10000, by = 2000),
  cex.axis = .7
)
```


##### Otros 
```{r casos-otros-acumulados}
plot(
  covid$FECHA,
  covid$positivos,
  type = "l",
  xaxt = "n",
  yaxt = "n",
  main = "Casos acumulados de COVID en Costa Rica",
  xlab = "Fecha",
  ylab = "Casos fallecidos",
  col = "blue"
)

# Casos activos
lines(covid$FECHA, covid$activos, col="red")

# Casos fallecidos
lines(covid$FECHA, covid$fallecidos, col="black")

# Casos recuperados
lines(covid$FECHA, covid$RECUPERADOS, col="green")

legend(
  x = "topleft",
  inset = 0.03,
  legend = c("Positivos", "Activos", "Fallecidos", "Recuperados"),
  col = c("blue", "red", "black", "green"), 
  lty = 1, 
  cex = 0.7
)

axis(side = 1,
     covid$FECHA,
     tick = FALSE,
     format(covid$FECHA, "%m-%y"),
     cex.axis = .7)
 
axis(
  side = 2,
  covid$positivos,
  labels = TRUE,  
  at = seq(0, 1000000, by = 200000),
  cex.axis = .7)

```









































